using CRM.Application.Ports.Persistence;
using CRM.Domain.Enums;
using CRM.Domain.OpportunityManagement;

namespace CRM.Application.OpportunityManagement;

public sealed class OpportunityManagementService(IOpportunityFoundationStore store) : IOpportunityManagementService
{
    private const string PersistenceMode="NonProductionSeam";
    public async Task<IReadOnlyCollection<OpportunityManagementApplicationOpportunity>> GetAllAsync(CancellationToken ct=default){ct.ThrowIfCancellationRequested(); return (await store.GetAllAsync(ct)).Select(ToApp).ToArray();}
    public async Task<OpportunityManagementApplicationOpportunity?> GetByIdAsync(string id,CancellationToken ct=default){ct.ThrowIfCancellationRequested(); var x=await store.GetByIdAsync(id,ct); return x is null?null:ToApp(x);}
    public async Task<OpportunityManagementApplicationResult> CreateAsync(OpportunityManagementCreateRequest r,CancellationToken ct=default){ct.ThrowIfCancellationRequested(); var e=OpportunityPipelinePolicy.Evaluate(new(OpportunityPipelineOperation.Create,null,r.AccountName,r.ExpectedValue,r.Currency,r.Probability,r.PipelineId,r.StageId,r.Stages,r.LeadId,r.ContactId,r.AccountId,r.ActivityId)); if(!e.Success)return Result(e,null); var record=FromEvaluation(Guid.NewGuid().ToString(),e); var saved=await store.SaveAsync(record,ct); return Result(e with { OpportunityId=saved.Id },ToApp(saved));}
    public async Task<OpportunityManagementApplicationResult> UpdateAsync(string id,OpportunityManagementUpdateRequest r,CancellationToken ct=default){ct.ThrowIfCancellationRequested(); var x=await store.GetByIdAsync(id,ct); if(x is null)return NotFound(OpportunityPipelineOperation.Update,id); var e=OpportunityPipelinePolicy.Evaluate(new(OpportunityPipelineOperation.Update,id,r.AccountName,r.ExpectedValue,r.Currency,r.Probability,r.PipelineId,r.StageId,r.Stages,r.LeadId,r.ContactId,r.AccountId,r.ActivityId,Snapshot(x))); if(!e.Success)return Result(e,null); if(!e.Changed)return Result(e,ToApp(x)); var saved=await store.SaveAsync(FromEvaluation(id,e),ct); return Result(e,ToApp(saved));}
    public async Task<OpportunityManagementApplicationResult> ProgressAsync(string id,OpportunityManagementProgressRequest r,CancellationToken ct=default){ct.ThrowIfCancellationRequested(); var x=await store.GetByIdAsync(id,ct); if(x is null)return NotFound(OpportunityPipelineOperation.Progress,id); var e=OpportunityPipelinePolicy.Evaluate(new(OpportunityPipelineOperation.Progress,id,x.AccountName,x.ExpectedValue,x.Currency,x.Probability,x.PipelineId,r.StageId,r.Stages,x.LeadId,x.ContactId,x.AccountId,x.ActivityId,Snapshot(x))); if(!e.Success)return Result(e,null); if(!e.Changed)return Result(e,ToApp(x)); var saved=await store.SaveAsync(FromEvaluation(id,e),ct); return Result(e,ToApp(saved));}
    public Task<OpportunityManagementApplicationResult> WinAsync(string id,CancellationToken ct=default)=>Terminal(id,OpportunityPipelineOperation.Win,ct);
    public Task<OpportunityManagementApplicationResult> LoseAsync(string id,CancellationToken ct=default)=>Terminal(id,OpportunityPipelineOperation.Lose,ct);
    public Task<OpportunityManagementApplicationResult> CancelAsync(string id,CancellationToken ct=default)=>Terminal(id,OpportunityPipelineOperation.Cancel,ct);
    private async Task<OpportunityManagementApplicationResult> Terminal(string id,OpportunityPipelineOperation op,CancellationToken ct){ct.ThrowIfCancellationRequested(); var x=await store.GetByIdAsync(id,ct); if(x is null)return NotFound(op,id); var stages=new[]{new OpportunityPipelineStageDefinition(x.StageId,"Current",1)}; var e=OpportunityPipelinePolicy.Evaluate(new(op,id,x.AccountName,x.ExpectedValue,x.Currency,x.Probability,x.PipelineId,x.StageId,stages,x.LeadId,x.ContactId,x.AccountId,x.ActivityId,Snapshot(x))); if(!e.Success)return Result(e,null); if(!e.Changed)return Result(e,ToApp(x)); var saved=await store.SaveAsync(FromEvaluation(id,e),ct); return Result(e,ToApp(saved));}
    private static OpportunityPipelineSnapshot Snapshot(OpportunityFoundationRecord x)=>new(x.Id,x.AccountName,x.ExpectedValue,x.Currency,x.Probability,x.PipelineId,x.StageId,x.Status,x.LeadId,x.ContactId,x.AccountId,x.ActivityId);
    private static OpportunityFoundationRecord FromEvaluation(string id,OpportunityPipelineRuleResult e)=>new(id,e.NormalizedAccountName!,e.ExpectedValue,e.NormalizedCurrency!,e.Probability,e.PipelineId!,e.StageId!,e.ResultStatus,e.LeadId,e.ContactId,e.AccountId,e.ActivityId);
    private static OpportunityManagementApplicationOpportunity ToApp(OpportunityFoundationRecord x)=>new(x.Id,x.AccountName,x.ExpectedValue,x.Currency,x.Probability,x.PipelineId,x.StageId,x.Status,x.LeadId,x.ContactId,x.AccountId,x.ActivityId,PersistenceMode,false);
    private static OpportunityManagementApplicationResult Result(OpportunityPipelineRuleResult e,OpportunityManagementApplicationOpportunity? x)=>new(x?.Id??e.OpportunityId,e.Operation,e.Allowed,e.Changed,e.ErrorCode.ToString(),e.Message,x?.Status??e.ResultStatus,x);
    private static OpportunityManagementApplicationResult NotFound(OpportunityPipelineOperation op,string id)=>new(id,op,false,false,OpportunityPipelineErrorCode.OpportunityNotFound.ToString(),"Opportunity was not found.",null,null);
}
