using Xunit;

namespace CRM.ArchitectureTests;

public sealed class OpportunityCrossLayerGuardrailTests
{
    private static string Root(){var c=AppContext.BaseDirectory;while(!string.IsNullOrWhiteSpace(c)){if(File.Exists(Path.Combine(c,"CRM.sln")))return c;c=Directory.GetParent(c)?.FullName;}throw new DirectoryNotFoundException();}
    [Fact] public void Frontend_UsesFoundationRoutesOnly_AndNoDelete(){var r=Root();var s=File.ReadAllText(Path.Combine(r,"frontend","crm-web","src","main.ts"));var a=s.IndexOf("type OpportunityStatus");var b=s.IndexOf("type ActivityType");var o=s[a..b];Assert.Contains("/api/crm/foundation/opportunities",o,StringComparison.Ordinal);Assert.DoesNotContain("/api/crm/opportunities",o,StringComparison.Ordinal);Assert.DoesNotContain("deleteOpportunity",o,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain(".delete<",o,StringComparison.OrdinalIgnoreCase);}
    [Fact] public void Frontend_StageCatalog_UsesGuidIdsAndStrictOrder(){var r=Root();var s=File.ReadAllText(Path.Combine(r,"frontend","crm-web","src","main.ts"));var a=s.IndexOf("const opportunityPipelineStages");var b=s.IndexOf("interface FoundationOpportunity",a);var c=s[a..b];foreach(var id in new[]{"cccccccc-cccc-cccc-cccc-cccccccccccc","dddddddd-dddd-dddd-dddd-dddddddddddd","eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee","ffffffff-ffff-ffff-ffff-ffffffffffff"}) Assert.Contains(id,c,StringComparison.Ordinal);foreach(var order in new[]{"order: 1","order: 2","order: 3","order: 4"}) Assert.Contains(order,c,StringComparison.Ordinal);Assert.Contains("current.order + 1",s,StringComparison.Ordinal);}
    [Fact] public void Frontend_TerminalLifecycle_IsReadOnlyAndDuplicateProtected(){var r=Root();var s=File.ReadAllText(Path.Combine(r,"frontend","crm-web","src","main.ts"));var a=s.IndexOf("type OpportunityStatus");var b=s.IndexOf("type ActivityType");var o=s[a..b];Assert.Contains("opportunity.status !== 'Open' || this.isSubmitting()",o,StringComparison.Ordinal);Assert.Contains("selectedOpportunityReadonly()",o,StringComparison.Ordinal);Assert.Contains("opportunityForm.disable",o,StringComparison.Ordinal);Assert.Contains("isSubmitting.set(true)",o,StringComparison.Ordinal);}
    [Fact] public void Api_AndProgram_KeepProductiveOpportunityLocked(){var r=Root();var p=File.ReadAllText(Path.Combine(r,"src","CRM.Api","Program.cs"));Assert.Contains("/api/crm/foundation/opportunities",p,StringComparison.Ordinal);foreach(var x in new[]{"MapGet(\"/api/crm/opportunities","MapPost(\"/api/crm/opportunities","MapPut(\"/api/crm/opportunities","MapDelete(\"/api/crm/opportunities","MapDelete(\"/api/crm/foundation/opportunities"}) Assert.DoesNotContain(x,p,StringComparison.OrdinalIgnoreCase);}
}
