using System.Net; using System.Net.Http.Json; using System.Text.Json; using Microsoft.AspNetCore.Mvc.Testing; using Xunit;
namespace CRM.UnitTests;
public sealed class TagFoundationApiTests
{
 const string Seed="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa";
 [Fact] public async Task ListDetailCreate_AreAvailable(){using var f=new WebApplicationFactory<Program>();using var c=f.CreateClient();Assert.Equal(HttpStatusCode.OK,(await c.GetAsync("/api/crm/foundation/tags")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.GetAsync($"/api/crm/foundation/tags/{Seed}")).StatusCode);var r=await c.PostAsJsonAsync("/api/crm/foundation/tags",new{name=" VIP ",description=" api ",relatedEntityType="Lead",relatedEntityId=Guid.NewGuid().ToString("D")});using var b=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Assert.Equal(HttpStatusCode.OK,r.StatusCode);Assert.True(b.RootElement.GetProperty("changed").GetBoolean());Assert.False(b.RootElement.GetProperty("productiveCrudEnabled").GetBoolean());Assert.False(b.RootElement.GetProperty("portalIdentityRuntimeEnabled").GetBoolean());Assert.Equal("VIP",b.RootElement.GetProperty("tag").GetProperty("name").GetString());}
 [Fact] public async Task ValidationMissingArchiveConflict_MapSafely(){using var f=new WebApplicationFactory<Program>();using var c=f.CreateClient();var bad=await c.PostAsJsonAsync("/api/crm/foundation/tags",new{name=" ",relatedEntityType="Contact",relatedEntityId="bad"});Assert.Equal(HttpStatusCode.BadRequest,bad.StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await c.GetAsync($"/api/crm/foundation/tags/{Guid.NewGuid():D}")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.PostAsync($"/api/crm/foundation/tags/{Seed}/archive",null)).StatusCode);var again=await c.PostAsync($"/api/crm/foundation/tags/{Seed}/archive",null);using var body=JsonDocument.Parse(await again.Content.ReadAsStringAsync());Assert.False(body.RootElement.GetProperty("changed").GetBoolean());var conflict=await c.PutAsJsonAsync($"/api/crm/foundation/tags/{Seed}",new{name="Changed",description="x",relatedEntityType="Contact",relatedEntityId="11111111-1111-1111-1111-111111111111"});Assert.Equal(HttpStatusCode.Conflict,conflict.StatusCode);}
 [Fact] public async Task ProductiveAndDeleteRemainUnavailable(){using var f=new WebApplicationFactory<Program>();using var c=f.CreateClient();Assert.Equal(HttpStatusCode.NotFound,(await c.GetAsync("/api/crm/tags")).StatusCode);var d=await c.DeleteAsync($"/api/crm/foundation/tags/{Seed}");Assert.True(d.StatusCode is HttpStatusCode.NotFound or HttpStatusCode.MethodNotAllowed);}
}
