using System.Net; using System.Net.Http.Json; using System.Text.Json; using Microsoft.AspNetCore.Mvc.Testing; using Xunit;
namespace CRM.UnitTests;
public sealed class TagHardeningTests
{
 const string Seed="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa", Related="11111111-1111-1111-1111-111111111111";
 [Fact] public async Task Update_NoChange_ReturnsChangedFalse(){using var f=new WebApplicationFactory<Program>();using var c=f.CreateClient();var r=await c.PutAsJsonAsync($"/api/crm/foundation/tags/{Seed}",new{name="Priority",description="Synthetic foundation tag",relatedEntityType="Contact",relatedEntityId=Related});using var b=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Assert.Equal(HttpStatusCode.OK,r.StatusCode);Assert.False(b.RootElement.GetProperty("changed").GetBoolean());}
 [Fact] public async Task AssignmentOnlyChange_ReturnsChangedTrue(){using var f=new WebApplicationFactory<Program>();using var c=f.CreateClient();var r=await c.PutAsJsonAsync($"/api/crm/foundation/tags/{Seed}",new{name="Priority",description="Synthetic foundation tag",relatedEntityType="Lead",relatedEntityId=Guid.NewGuid().ToString("D")});using var b=JsonDocument.Parse(await r.Content.ReadAsStringAsync());Assert.Equal(HttpStatusCode.OK,r.StatusCode);Assert.True(b.RootElement.GetProperty("changed").GetBoolean());}
 [Fact] public async Task HttpBoundaries_AreEnforced(){using var f=new WebApplicationFactory<Program>();using var c=f.CreateClient();var ok=await c.PostAsJsonAsync("/api/crm/foundation/tags",new{name=new string('x',80),description=new string('y',500)});Assert.Equal(HttpStatusCode.OK,ok.StatusCode);var longName=await c.PostAsJsonAsync("/api/crm/foundation/tags",new{name=new string('x',81)});Assert.Equal(HttpStatusCode.BadRequest,longName.StatusCode);var longDesc=await c.PostAsJsonAsync("/api/crm/foundation/tags",new{name="tag",description=new string('y',501)});Assert.Equal(HttpStatusCode.BadRequest,longDesc.StatusCode);}
 [Fact] public async Task InvalidAssignment_IsBadRequest(){using var f=new WebApplicationFactory<Program>();using var c=f.CreateClient();var r=await c.PostAsJsonAsync("/api/crm/foundation/tags",new{name="tag",relatedEntityType="Contact",relatedEntityId="bad"});Assert.Equal(HttpStatusCode.BadRequest,r.StatusCode);}
}
