$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$paths = @(
    "docs/roadmap/crm-sprint-10-p37-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation.md",
    "docs/roadmap/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-go-no-go.md",
    "docs/roadmap/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-risk-register.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-matrix.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-preflight.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-prerequisites.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-blockers.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-artifacts.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-command-matrix.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-evidence.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-readiness-snapshot.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-security-checklist.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-architecture-checklist.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-devops-checklist.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-qa-uat-checklist.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-monitoring-checklist.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-rollback-checklist.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-communications.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-hypercare.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-portal-first-boundaries.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-common-db-boundaries.md",
    "docs/integration/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-p38-conditions.md",
    "docs/operations/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-runbook.md",
    "docs/security/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-security-decision.md",
    "tools/check-crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation-guardrails.ps1",
    "tools/verify-crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation.ps1",
    "tools/crm-controlled-runtime-pilot-first-slice-nonproduction-activation-controlled-execution-preparation.ps1",
    "codex/TASKS.md"
)
foreach ($path in $paths) { if (-not (Test-Path (Join-Path $root $path))) { throw "Missing expected P37 file: $path" } }
$joined = ($paths | ForEach-Object { Get-Content (Join-Path $root $_) -Raw }) -join "`n"
$p37Only = ($paths | Where-Object { $_ -ne "codex/TASKS.md" } | ForEach-Object { Get-Content (Join-Path $root $_) -Raw }) -join "`n"
foreach ($marker in @(
    "CrmSprint10P37ControlledRuntimePilotFirstSliceNonProductionActivationControlledExecutionPreparationExists: true",
    "CrmSprint10P36FinalGoNoGoGateReviewed: true",
    "PortalSprint21ContractAlignmentReviewed: true",
    "ProductizationStatus: PreparationOnly",
    "ProductionActivationDecision: NoGo",
    "CrmProductionReady: false",
    "FirstSliceNonProductionActivationControlledExecutionPreparationPrepared: true",
    "FirstSliceNonProductionActivationControlledExecutionPreparationMatrixPrepared: true",
    "NonProductionActivationControlledExecutionPreparationOnly: true",
    "NonProductionActivationControlledExecutionPrepared: true",
    "NonProductionActivationControlledExecutionExecuted: false",
    "NonProductionActivationFinalGoNoGoDecision: NoGo",
    "NonProductionActivationFinalGoApproved: false",
    "NonProductionActivationExecutionPlanExecuted: false",
    "NonProductionActivationExecutionApprovalExecuted: false",
    "NonProductionActivationReadinessApprovedForExecution: false",
    "DryRunControlledExecutionValidated: true",
    "DryRunExecuted: true",
    "DryRunExternalCallExecuted: false",
    "DryRunPortalCallExecuted: false",
    "DryRunActivationExecuted: false",
    "ExplicitApprovalExecuted: false",
    "NonProductionActivationControlledImplementationExecuted: false",
    "ConditionalGoFutureExecuted: false",
    "NonProductionActivationExecuted: false",
    "ConditionalFutureGoExecuted: false",
    "RuntimePortalCouplingEnabled: false",
    "RuntimePortalCallsEnabled: false",
    "ProductivePortalNavigationEnabled: false",
    "ProductivePortalGatewayRoutesEnabled: false",
    "RealPortalPrivateUrlsPresent: false",
    "PortalServicesInCrmCompose: false",
    "CommonDbRuntimeEnabled: false",
    "RealCommonDbConnectionConfigured: false",
    "SharedPortalTablesAccessEnabled: false",
    "CrossDomainMigrationsPresent: false",
    "PortalDatabaseDirectAccessEnabled: false",
    "PortalAuthDuplicated: false",
    "PortalMenuDuplicated: false",
    "PortalPermissionsDuplicated: false",
    "PortalAuditDuplicated: false",
    "PortalNotificationDuplicated: false",
    "PortalConfigurationDuplicated: false",
    "SsoOidcProductionConfigured: false",
    "RealSecretProviderConfigured: false",
    "RealNotificationProviderConfigured: false",
    "RealObservabilityProviderConfigured: false",
    "BrowserTokenStorageDetected: false",
    "SecretsPresent: false",
    "EnvRealFileCommitted: false",
    "PrivateUrlsPresent: false",
    "RealDataPresent: false",
    "ControlledRuntimePilotFirstSliceNonProductionActivationControlledExecutionPreparationReadiness: ControlledExecutionPreparationPreparedNoGoNow",
    "NextGate: CrmSprint10P38ControlledRuntimePilotFirstSliceNonProductionActivationControlledExecutionPreparationValidation"
)) { if ($joined -notlike "*$marker*") { throw "Missing required P37 marker: $marker" } }
foreach ($pattern in @(("client" + "_secret="), ("BEGIN " + "CERTIFICATE"), ("PRIVATE " + "KEY"), ("local" + "Storage"), ("session" + "Storage"), ("http" + "://"), ("https" + "://"), ("Http" + "Client"), ("Use" + "SqlServer"), ("Password" + "="), ("User " + "ID="))) { if ($p37Only -like "*$pattern*") { throw "Forbidden P37 content detected: $pattern" } }
$compose = Get-Content (Join-Path $root "docker-compose.yml") -Raw
if ($compose -match "mcr\.microsoft\.com/mssql|1433:1433|PortalCorporativo|portal.*image:|portal.*build:") { throw "CRM compose appears to define SQL Server or Portal services." }
Write-Host "PASS CRM P37 controlled execution preparation guardrails passed."
