$ErrorActionPreference='Stop'
$root='C:\Users\ChristianYepez\source\repos\CRM_S20_ISOLATED'
Set-Location $root
function W([string]$p,[string]$t){$full=Join-Path $root $p;$dir=Split-Path $full -Parent;if(!(Test-Path $dir)){New-Item -ItemType Directory -Path $dir -Force|Out-Null};[IO.File]::WriteAllText($full,$t,[Text.UTF8Encoding]::new($false))}
function Branch([string]$b){git switch -c $b | Out-Host}
function Commit([string]$m){git add -A;git commit -m $m | Out-Host}
function Regression([bool]$angular=$false){dotnet build CRM.sln -c Release;if($LASTEXITCODE){throw 'build failed'};dotnet test tests\CRM.UnitTests\CRM.UnitTests.csproj -c Release --no-build;if($LASTEXITCODE){throw 'unit failed'};dotnet test tests\CRM.ArchitectureTests\CRM.ArchitectureTests.csproj -c Release --no-build;if($LASTEXITCODE){throw 'arch failed'};if($angular){Push-Location frontend\crm-web;npm test;if($LASTEXITCODE){throw 'angular test failed'};npm run build;if($LASTEXITCODE){throw 'angular build failed'};Pop-Location}}
function StopPorts([int[]]$ports){foreach($port in $ports){$ls=Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue;foreach($l in $ls){$p=Get-Process -Id $l.OwningProcess -ErrorAction SilentlyContinue;$ci=Get-CimInstance Win32_Process -Filter "ProcessId=$($l.OwningProcess)" -ErrorAction SilentlyContinue;if(($p.Path -like '*CRM_S20_ISOLATED*CRM.Api*') -or ($ci.CommandLine -like '*CRM_S20_ISOLATED*')){Stop-Process -Id $l.OwningProcess -Force -ErrorAction SilentlyContinue}}}}
function WaitUrl([string]$u){for($i=0;$i-lt80;$i++){try{$x=Invoke-WebRequest -UseBasicParsing $u -TimeoutSec 2;if($x.StatusCode-eq200){return}}catch{};Start-Sleep -Milliseconds 500};throw "timeout $u"}
function Integrate([int]$s,[string]$key,[int]$apiPort,[int]$webPort){
 $proxy="{`n  `"/api`": { `"target`": `"http://127.0.0.1:$apiPort`", `"secure`": false, `"changeOrigin`": true }`n}`n";W "frontend\crm-web\proxy.s$s-06.json" $proxy
 $env:ASPNETCORE_ENVIRONMENT='Development';$api=Start-Process dotnet -ArgumentList @('run','--project','src\CRM.Api\CRM.Api.csproj','-c','Release','--no-build','--urls',"http://127.0.0.1:$apiPort") -WorkingDirectory $root -PassThru -WindowStyle Hidden
 $web=Start-Process '.\node_modules\.bin\ng.cmd' -ArgumentList @('serve','--host','127.0.0.1','--port',"$webPort",'--proxy-config',"proxy.s$s-06.json") -WorkingDirectory (Join-Path $root 'frontend\crm-web') -PassThru -WindowStyle Hidden
 try{WaitUrl "http://127.0.0.1:$apiPort/health";WaitUrl "http://127.0.0.1:$webPort/foundation/insights";$json=& "$root\tools\run-crm-insight-local-integration.ps1" -Key $key -BaseUrl "http://127.0.0.1:$apiPort" -FrontendUrl "http://127.0.0.1:$webPort" -Sprint "$s";W "docs\roadmap\crm-sprint-$s-s$s-06-local-integration-result.json" $json;$o=$json|ConvertFrom-Json;W "docs\roadmap\crm-sprint-$s-s$s-06-local-integration-validation.md" "# CRM Sprint $s S$s-06 - Local Integration`n`nDecision: Implemented`nInsightKey: $key`nLatencySamples: $($o.IntegrationLatencySamples)`nLatencyAverageMs: $($o.LatencyAverageMs)`nLatencyP95Ms: $($o.LatencyP95Ms)`nMutationRoutesAvailable: false`nProductiveRouteAvailable: false`nPortalRuntimeEnabled: false`nCommonDbRuntimeEnabled: false`n"}finally{StopPorts @($apiPort,$webPort);Stop-Process -Id $api.Id -Force -ErrorAction SilentlyContinue;Stop-Process -Id $web.Id -Force -ErrorAction SilentlyContinue}}
function AddInsight([int]$s,[string]$slug,[string]$constName,[string]$key,[string]$title,[string]$metricExpr,[string]$nextName){
 Branch "crm-sprint-$s-p1-$slug-functional-baseline";W "docs\roadmap\crm-sprint-$s-$slug-functional-baseline.md" "# CRM Sprint $s - $title Foundation`n`nScope: read-only FoundationMock reporting insight.`nNo productive routes, mutations, Portal runtime, Common DB, external connectors or real data.`nSlices: S$s-01 contracts/catalog; S$s-02 provider/service parity; S$s-03 API parity; S$s-04 frontend parity; S$s-05 hardening; S$s-06 local integration; S$s-07 closure.`n";W "codex\prompts\sprint-$s-$slug-s$s-01.md" "Implement Sprint $s S$s-01 for $title using Reporting Insights foundation infrastructure.";W 'codex\next-task.md' "# Next task`nSprint: $s`nSlice: S$s-01`n";Commit "docs(crm): define $slug functional baseline"
 Branch "crm-sprint-$s-s$s-01-$slug-contract-catalog";$contracts=Get-Content 'src\CRM.Domain\ReportingInsights\ReportingInsightContracts.cs' -Raw;$contracts=[regex]::Replace($contracts,'(public static class ReportingInsightKeys \{[^}]*)\}',{param($m) $m.Groups[1].Value+" public const string $constName=`"$key`"; }"});W 'src\CRM.Domain\ReportingInsights\ReportingInsightContracts.cs' $contracts;$provider=Get-Content 'src\CRM.Infrastructure\ReportingInsights\InMemoryReportingInsightFoundationProvider.cs' -Raw;$provider=$provider.Replace('  // INSIGHT_ITEMS',"  ,new(ReportingInsightKeys.$constName,`"$title`",[$metricExpr],`"FoundationMock`")`r`n  // INSIGHT_ITEMS");W 'src\CRM.Infrastructure\ReportingInsights\InMemoryReportingInsightFoundationProvider.cs' $provider;W "tests\CRM.UnitTests\Sprint${s}InsightCatalogTests.cs" "using CRM.Domain.ReportingInsights;using Xunit;namespace CRM.UnitTests;public sealed class Sprint${s}InsightCatalogTests{[Fact]public void Insight_IsValid(){var x=new ReportingInsightSnapshot(`"$key`",`"$title`",[$metricExpr],`"FoundationMock`");var r=ReportingInsightPolicy.Validate(x);Assert.True(r.Valid);Assert.NotNull(r.Snapshot);}}";W "codex\prompts\sprint-$s-$slug-s$s-02.md" "Implement S$s-02 provider/service parity for $title.";W 'codex\next-task.md' "# Next task`nSprint: $s`nSlice: S$s-02`n";dotnet test tests\CRM.UnitTests\CRM.UnitTests.csproj -c Release --filter Sprint${s}InsightCatalogTests;if($LASTEXITCODE){throw "S$s-01 failed"};Commit "feat(crm): add $slug insight catalog"
 Branch "crm-sprint-$s-s$s-02-$slug-provider-service-parity";W "tests\CRM.UnitTests\Sprint${s}InsightServiceTests.cs" "using CRM.Application.ReportingInsights;using Microsoft.AspNetCore.Mvc.Testing;using Microsoft.Extensions.DependencyInjection;using Xunit;namespace CRM.UnitTests;public sealed class Sprint${s}InsightServiceTests{[Fact]public async Task Insight_IsServedReadOnly(){using var f=new WebApplicationFactory<Program>();var svc=f.Services.GetRequiredService<IReportingInsightReadService>();var x=await svc.GetByKeyAsync(`"$key`");Assert.NotNull(x);Assert.Equal(`"FoundationMock`",x!.SourceMode);Assert.False(x.ProductiveRuntimeEnabled);Assert.False(x.PortalRuntimeEnabled);Assert.False(x.CommonDbRuntimeEnabled);}}";W "codex\prompts\sprint-$s-$slug-s$s-03.md" "Implement S$s-03 API parity for $title.";W 'codex\next-task.md' "# Next task`nSprint: $s`nSlice: S$s-03`n";dotnet test tests\CRM.UnitTests\CRM.UnitTests.csproj -c Release --filter Sprint${s}InsightServiceTests;if($LASTEXITCODE){throw "S$s-02 failed"};Commit "test(crm): validate $slug provider service parity"
 Branch "crm-sprint-$s-s$s-03-$slug-api-parity";W "tests\CRM.UnitTests\Sprint${s}InsightApiTests.cs" "using System.Net;using Microsoft.AspNetCore.Mvc.Testing;using Xunit;namespace CRM.UnitTests;public sealed class Sprint${s}InsightApiTests{[Fact]public async Task Detail_IsGetOnly(){using var f=new WebApplicationFactory<Program>();using var c=f.CreateClient();Assert.Equal(HttpStatusCode.OK,(await c.GetAsync(`"/api/crm/foundation/insights/$key`")).StatusCode);using var q=new HttpRequestMessage(HttpMethod.Post,`"/api/crm/foundation/insights/$key`");var r=await c.SendAsync(q);Assert.True(r.StatusCode is HttpStatusCode.NotFound or HttpStatusCode.MethodNotAllowed);Assert.Equal(HttpStatusCode.NotFound,(await c.GetAsync(`"/api/crm/insights/$key`")).StatusCode);}}";W "codex\prompts\sprint-$s-$slug-s$s-04.md" "Implement S$s-04 frontend parity for $title using shared read-only insights page.";W 'codex\next-task.md' "# Next task`nSprint: $s`nSlice: S$s-04`n";dotnet test tests\CRM.UnitTests\CRM.UnitTests.csproj -c Release --filter Sprint${s}InsightApiTests;if($LASTEXITCODE){throw "S$s-03 failed"};Commit "test(crm): validate $slug foundation api parity"
 Branch "crm-sprint-$s-s$s-04-$slug-frontend-parity";W "tests\CRM.ArchitectureTests\Sprint${s}InsightFrontendTests.cs" "using Xunit;namespace CRM.ArchitectureTests;public sealed class Sprint${s}InsightFrontendTests{static string R(){var c=AppContext.BaseDirectory;while(!string.IsNullOrWhiteSpace(c)){if(File.Exists(Path.Combine(c,`"CRM.sln`")))return c;c=Directory.GetParent(c)?.FullName;}throw new DirectoryNotFoundException();}[Fact]public void SharedPage_RemainsReadOnly(){var m=File.ReadAllText(Path.Combine(R(),`"frontend`",`"crm-web`",`"src`",`"main.ts`"));Assert.Contains(`"foundation/insights`",m);Assert.Contains(`"/api/crm/foundation/insights`",m);}}";W "codex\prompts\sprint-$s-$slug-s$s-05.md" "Implement S$s-05 hardening for $title.";W 'codex\next-task.md' "# Next task`nSprint: $s`nSlice: S$s-05`n";dotnet test tests\CRM.ArchitectureTests\CRM.ArchitectureTests.csproj -c Release --filter Sprint${s}InsightFrontendTests;if($LASTEXITCODE){throw "S$s-04 failed"};Commit "test(crm): validate $slug frontend parity"
 Branch "crm-sprint-$s-s$s-05-$slug-hardening";W "tests\CRM.UnitTests\Sprint${s}InsightHardeningTests.cs" "using CRM.Application.ReportingInsights;using Microsoft.AspNetCore.Mvc.Testing;using Microsoft.Extensions.DependencyInjection;using Xunit;namespace CRM.UnitTests;public sealed class Sprint${s}InsightHardeningTests{[Fact]public async Task FlagsAndMetrics_AreSafe(){using var f=new WebApplicationFactory<Program>();var svc=f.Services.GetRequiredService<IReportingInsightReadService>();var x=await svc.GetByKeyAsync(`"$key`");Assert.NotNull(x);Assert.All(x!.Metrics,m=>Assert.True(m.Value>=0));Assert.Equal(`"FoundationMock`",x.SourceMode);Assert.False(x.ProductiveRuntimeEnabled);Assert.False(x.PortalRuntimeEnabled);Assert.False(x.CommonDbRuntimeEnabled);}}";W "codex\prompts\sprint-$s-$slug-s$s-06.md" "Run S$s-06 local HTTP integration for $title.";W 'codex\next-task.md' "# Next task`nSprint: $s`nSlice: S$s-06`n";Regression $true;Commit "test(crm): harden $slug insight guardrails"
 Branch "crm-sprint-$s-s$s-06-$slug-local-integration";Integrate $s $key (8103+$s-26) (4216+$s-26);W "codex\prompts\sprint-$s-$slug-s$s-07.md" "Close Sprint $s $title after full regression.";W 'codex\next-task.md' "# Next task`nSprint: $s`nSlice: S$s-07`n";Commit "test(crm): validate $slug local integration"
 Branch "crm-sprint-$s-s$s-07-$slug-closure";Regression $true;W "docs\releases\crm-sprint-$s-$slug-closure.md" "# CRM Sprint $s - $title Closure`n`nDecision: Closed`nFoundationMock: true`nReadOnly: true`nProductiveRoutes: false`nPortalRuntime: false`nCommonDbRuntime: false`nExternalConnectors: false`nRealData: false`nRegression: PASS`n";if($s -lt 30){W 'codex\next-task.md' "# Next task`nSprint: $($s+1)`nSlice: P1`n"}else{W 'codex\next-task.md' "# Next task`nSprint: 30`nSlice: COMPLETE`nObjective: CRM foundation roadmap through Sprint 30 closed`n"};Commit "docs(crm): close $slug sprint"
}
# Close Sprint 26 from current S26-06 branch
Integrate 26 'leads-funnel' 8103 4216
W 'codex\prompts\sprint-26-leads-funnel-s26-07.md' 'Close Sprint 26 Leads Funnel after full regression.';W 'codex\next-task.md' "# Next task`nSprint: 26`nSlice: S26-07`n";Commit 'test(crm): validate leads funnel local integration'
Branch 'crm-sprint-26-s26-07-leads-funnel-closure';Regression $true;W 'docs\releases\crm-sprint-26-leads-funnel-closure.md' "# CRM Sprint 26 - Leads Funnel Closure`n`nDecision: Closed`nFoundationMock: true`nReadOnly: true`nProductiveRoutes: false`nRegression: PASS`n";W 'codex\next-task.md' "# Next task`nSprint: 27`nSlice: P1`n";Commit 'docs(crm): close leads funnel sprint'
AddInsight 27 'opportunities-pipeline' 'OpportunitiesPipeline' 'opportunities-pipeline' 'Opportunities Pipeline' 'new("OpportunitiesWon",12m,"Count"),new("OpportunitiesLost",5m,"Count"),new("PipelineValue",245000m,"Amount")' 'Sales Activities'
AddInsight 28 'sales-activities' 'SalesActivities' 'sales-activities' 'Sales Activities' 'new("ActivitiesCompleted",64m,"Count"),new("FollowUpsPending",17m,"Count"),new("AverageSalesCycleDays",29m,"Days")' 'Accounts and Contacts'
AddInsight 29 'accounts-contacts' 'AccountsContacts' 'accounts-contacts' 'Accounts and Contacts' 'new("AccountsActive",42m,"Count"),new("ContactsActive",118m,"Count")' 'CRM Executive Overview'
AddInsight 30 'crm-executive-overview' 'CrmExecutiveOverview' 'crm-executive-overview' 'CRM Executive Overview' 'new("LeadConversionRate",24.5m,"Percent"),new("QualifiedLeads",38m,"Count"),new("OpportunitiesWon",12m,"Count"),new("PipelineValue",245000m,"Amount"),new("ActivitiesCompleted",64m,"Count"),new("AccountsActive",42m,"Count")' 'Complete'
Regression $true
W 'docs\releases\crm-sprint-30-final-release-readiness.md' "# CRM Sprint 30 - Final Release Readiness`n`nRoadmapThroughSprint30: Closed`nFoundationRuntime: PASS`nUnitTests: PASS`nArchitectureTests: PASS`nAngularFoundationChecks: PASS`nAngularBuild: PASS`nProductiveActivation: NotPerformed`nPortalRuntime: Disabled`nCommonDbRuntime: Disabled`nExternalConnectors: Disabled`nRealData: NotUsed`nDELETE: Disabled`nProductionPort8094Touched: false`nDecision: FoundationObjectiveAchieved`n"
W 'codex\next-task.md' "# Next task`nSprint: 30`nSlice: COMPLETE`nObjective: Foundation roadmap through Sprint 30 achieved`n";Commit 'docs(crm): finalize sprint 30 release readiness'
Write-Host 'CRM_SPRINT_30_OBJECTIVE_ACHIEVED'
git status --short
git log -12 --oneline
