$ErrorActionPreference='Stop'
$root='C:\Users\ChristianYepez\source\repos\CRM_S20_ISOLATED';Set-Location $root
$master=[IO.File]::ReadAllText((Join-Path $root 'tools\complete-crm-sprints-26-30.ps1'));$defs=$master.Substring(0,$master.IndexOf('# Close Sprint 26 from current S26-06 branch'));Invoke-Expression $defs
# Finish Sprint 26 using already-running Development API 8103 + shared Angular 4216
$json=& "$root\tools\run-crm-insight-local-integration.ps1" -Key 'leads-funnel' -BaseUrl 'http://127.0.0.1:8103' -FrontendUrl 'http://127.0.0.1:4216' -Sprint '26';W 'docs\roadmap\crm-sprint-26-s26-06-local-integration-result.json' $json;$o=$json|ConvertFrom-Json;W 'docs\roadmap\crm-sprint-26-s26-06-local-integration-validation.md' "# CRM Sprint 26 S26-06 - Local Integration`n`nDecision: Implemented`nInsightKey: leads-funnel`nLatencySamples: $($o.IntegrationLatencySamples)`nLatencyAverageMs: $($o.LatencyAverageMs)`nLatencyP95Ms: $($o.LatencyP95Ms)`nMutationRoutesAvailable: false`nProductiveRouteAvailable: false`n"
W 'codex\prompts\sprint-26-leads-funnel-s26-07.md' 'Close Sprint 26 after full regression.';W 'codex\next-task.md' "# Next task`nSprint: 26`nSlice: S26-07`n";Commit 'test(crm): validate leads funnel local integration';StopPorts @(8103)
Branch 'crm-sprint-26-s26-07-leads-funnel-closure';Regression $true;W 'docs\releases\crm-sprint-26-leads-funnel-closure.md' "# CRM Sprint 26 - Leads Funnel Closure`n`nDecision: Closed`nFoundationMock: true`nReadOnly: true`nProductiveRoutes: false`nRegression: PASS`n";W 'codex\next-task.md' "# Next task`nSprint: 27`nSlice: P1`n";Commit 'docs(crm): close leads funnel sprint'
# Override integration: keep one shared Angular dev server on 4216; restart only API 8103 per sprint.
function Integrate([int]$s,[string]$key,[int]$apiPort,[int]$webPort){$env:ASPNETCORE_ENVIRONMENT='Development';$api=Start-Process dotnet -ArgumentList @('run','--project','src\CRM.Api\CRM.Api.csproj','-c','Release','--no-build','--urls','http://127.0.0.1:8103') -WorkingDirectory $root -PassThru -WindowStyle Hidden;try{WaitUrl 'http://127.0.0.1:8103/health';WaitUrl 'http://127.0.0.1:4216/foundation/insights';$j=& "$root\tools\run-crm-insight-local-integration.ps1" -Key $key -BaseUrl 'http://127.0.0.1:8103' -FrontendUrl 'http://127.0.0.1:4216' -Sprint "$s";W "docs\roadmap\crm-sprint-$s-s$s-06-local-integration-result.json" $j;$x=$j|ConvertFrom-Json;W "docs\roadmap\crm-sprint-$s-s$s-06-local-integration-validation.md" "# CRM Sprint $s S$s-06 - Local Integration`n`nDecision: Implemented`nInsightKey: $key`nLatencySamples: $($x.IntegrationLatencySamples)`nLatencyAverageMs: $($x.LatencyAverageMs)`nLatencyP95Ms: $($x.LatencyP95Ms)`nMutationRoutesAvailable: false`nProductiveRouteAvailable: false`nPortalRuntimeEnabled: false`nCommonDbRuntimeEnabled: false`n"}finally{StopPorts @(8103);Stop-Process -Id $api.Id -Force -ErrorAction SilentlyContinue}}
AddInsight 27 'opportunities-pipeline' 'OpportunitiesPipeline' 'opportunities-pipeline' 'Opportunities Pipeline' 'new("OpportunitiesWon",12m,"Count"),new("OpportunitiesLost",5m,"Count"),new("PipelineValue",245000m,"Amount")' 'Sales Activities'
AddInsight 28 'sales-activities' 'SalesActivities' 'sales-activities' 'Sales Activities' 'new("ActivitiesCompleted",64m,"Count"),new("FollowUpsPending",17m,"Count"),new("AverageSalesCycleDays",29m,"Days")' 'Accounts and Contacts'
AddInsight 29 'accounts-contacts' 'AccountsContacts' 'accounts-contacts' 'Accounts and Contacts' 'new("AccountsActive",42m,"Count"),new("ContactsActive",118m,"Count")' 'CRM Executive Overview'
AddInsight 30 'crm-executive-overview' 'CrmExecutiveOverview' 'crm-executive-overview' 'CRM Executive Overview' 'new("LeadConversionRate",24.5m,"Percent"),new("QualifiedLeads",38m,"Count"),new("OpportunitiesWon",12m,"Count"),new("PipelineValue",245000m,"Amount"),new("ActivitiesCompleted",64m,"Count"),new("AccountsActive",42m,"Count")' 'Complete'
Regression $true;W 'docs\releases\crm-sprint-30-final-release-readiness.md' "# CRM Sprint 30 - Final Release Readiness`n`nRoadmapThroughSprint30: Closed`nFoundationRuntime: PASS`nUnitTests: PASS`nArchitectureTests: PASS`nAngularFoundationChecks: PASS`nAngularBuild: PASS`nProductiveActivation: NotPerformed`nPortalRuntime: Disabled`nCommonDbRuntime: Disabled`nExternalConnectors: Disabled`nRealData: NotUsed`nDELETE: Disabled`nProductionPort8094Touched: false`nDecision: FoundationObjectiveAchieved`n";W 'codex\next-task.md' "# Next task`nSprint: 30`nSlice: COMPLETE`nObjective: Foundation roadmap through Sprint 30 achieved`n";Commit 'docs(crm): finalize sprint 30 release readiness';StopPorts @(4216);Write-Host 'CRM_SPRINT_30_OBJECTIVE_ACHIEVED';git status --short;git log -15 --oneline
