param([string]$BaseUrl='http://localhost:8093',[string]$FrontendUrl='http://127.0.0.1:4200')
$ErrorActionPreference='Stop'
function Req([string]$Method,[string]$Path,[object]$Body=$null){$sw=[Diagnostics.Stopwatch]::StartNew();try{$a=@{UseBasicParsing=$true;Method=$Method;Uri="$BaseUrl$Path";TimeoutSec=15};if($null-ne$Body){$a.Body=$Body|ConvertTo-Json -Depth 6 -Compress;$a.ContentType='application/json'};$r=Invoke-WebRequest @a;$sw.Stop();[pscustomobject]@{Method=$Method;Path=$Path;Status=[int]$r.StatusCode;Ms=$sw.ElapsedMilliseconds;Body=$r.Content}}catch{$sw.Stop();$s=0;$b='';if($_.Exception.Response){$s=[int]$_.Exception.Response.StatusCode};if($_.ErrorDetails.Message){$b=$_.ErrorDetails.Message};[pscustomobject]@{Method=$Method;Path=$Path;Status=$s;Ms=$sw.ElapsedMilliseconds;Body=$b}}}
function Ok($r,[int[]]$expected,[string]$name){if($r.Status -notin $expected){throw "$name expected $($expected -join '/') got $($r.Status): $($r.Body)"}}
$run=[guid]::NewGuid().ToString('N').Substring(0,8);$all=New-Object System.Collections.Generic.List[object]
foreach($p in @('/health','/health/live','/health/ready')){$r=Req GET $p;Ok $r @(200) "health $p";$all.Add($r)}
$list=Req GET '/api/crm/foundation/campaigns';Ok $list @(200) 'initial list';$all.Add($list);$initial=@($list.Body|ConvertFrom-Json).Count
function Payload([string]$name,[string]$start='2026-10-01',[string]$end='2026-10-31'){return @{name=$name;startDate=$start;endDate=$end}}
$create=Req POST '/api/crm/foundation/campaigns' (Payload "  S15 Integration Campaign $run  ");Ok $create @(200) 'create';$all.Add($create);$cj=$create.Body|ConvertFrom-Json;$id=$cj.id;if(!$id -or !$cj.changed -or $cj.campaign.name-ne"S15 Integration Campaign $run" -or $cj.status-ne'Draft'){throw 'create normalization failed'}
$detail=Req GET "/api/crm/foundation/campaigns/$id";Ok $detail @(200) 'detail';$all.Add($detail)
$update=Req PUT "/api/crm/foundation/campaigns/$id" (Payload "S15 Integration Campaign $run" '2026-10-02' '2026-11-01');Ok $update @(200) 'update';$all.Add($update);if(-not($update.Body|ConvertFrom-Json).changed){throw 'update should change'}
$uj=$update.Body|ConvertFrom-Json;$no=Req PUT "/api/crm/foundation/campaigns/$id" (Payload $uj.campaign.name ([string]$uj.campaign.startDate) ([string]$uj.campaign.endDate));Ok $no @(200) 'no change';$all.Add($no);if(($no.Body|ConvertFrom-Json).changed){throw 'no-change should be false'}
$bad=Req POST '/api/crm/foundation/campaigns' (Payload 'Bad range' '2026-12-31' '2026-12-01');Ok $bad @(400) 'invalid range';$all.Add($bad)
$missing=Req GET ("/api/crm/foundation/campaigns/"+[guid]::NewGuid().ToString('D'));Ok $missing @(404) 'missing';$all.Add($missing)
$activate=Req POST "/api/crm/foundation/campaigns/$id/activate";Ok $activate @(200) 'activate';$all.Add($activate);if(($activate.Body|ConvertFrom-Json).status-ne'Active'){throw 'activate state invalid'}
$repeatActivate=Req POST "/api/crm/foundation/campaigns/$id/activate";Ok $repeatActivate @(200) 'repeat activate';$all.Add($repeatActivate);if(($repeatActivate.Body|ConvertFrom-Json).changed){throw 'repeat activate changed'}
$terminalUpdate=Req PUT "/api/crm/foundation/campaigns/$id" (Payload 'Active edit' '2026-10-02' '2026-11-01');Ok $terminalUpdate @(409) 'active update conflict';$all.Add($terminalUpdate)
$complete=Req POST "/api/crm/foundation/campaigns/$id/complete";Ok $complete @(200) 'complete';$all.Add($complete);if(($complete.Body|ConvertFrom-Json).status-ne'Completed'){throw 'complete state invalid'}
$repeatComplete=Req POST "/api/crm/foundation/campaigns/$id/complete";Ok $repeatComplete @(200) 'repeat complete';$all.Add($repeatComplete);if(($repeatComplete.Body|ConvertFrom-Json).changed){throw 'repeat complete changed'}
$cancelCreate=Req POST '/api/crm/foundation/campaigns' (Payload "S15 Cancel Campaign $run" '2026-11-01' '2026-11-30');Ok $cancelCreate @(200) 'cancel create';$all.Add($cancelCreate);$cancelId=($cancelCreate.Body|ConvertFrom-Json).id
$cancel=Req POST "/api/crm/foundation/campaigns/$cancelId/cancel";Ok $cancel @(200) 'cancel';$all.Add($cancel);if(($cancel.Body|ConvertFrom-Json).status-ne'Cancelled'){throw 'cancel state invalid'}
$repeatCancel=Req POST "/api/crm/foundation/campaigns/$cancelId/cancel";Ok $repeatCancel @(200) 'repeat cancel';$all.Add($repeatCancel);if(($repeatCancel.Body|ConvertFrom-Json).changed){throw 'repeat cancel changed'}
$cancelUpdate=Req PUT "/api/crm/foundation/campaigns/$cancelId" (Payload 'Cancelled edit' '2026-11-01' '2026-11-30');Ok $cancelUpdate @(409) 'cancelled update';$all.Add($cancelUpdate)
$list2=Req GET '/api/crm/foundation/campaigns';Ok $list2 @(200) 'list after';$all.Add($list2);$ids=@(($list2.Body|ConvertFrom-Json)|%{$_.id});foreach($x in @($id,$cancelId)){if($ids -notcontains $x){throw "list missing $x"}}
foreach($n in @(@('GET','/api/crm/campaigns'),@('POST','/api/crm/campaigns'),@('PUT',"/api/crm/campaigns/$id"),@('DELETE',"/api/crm/campaigns/$id"))){$r=Req $n[0] $n[1];Ok $r @(404) "productive $($n[0])";$all.Add($r)}
$fd=Req DELETE "/api/crm/foundation/campaigns/$id";Ok $fd @(404,405) 'foundation delete';$all.Add($fd)
$fr=Invoke-WebRequest -UseBasicParsing "$FrontendUrl/foundation/campaigns" -TimeoutSec 15;if($fr.StatusCode-ne200){throw 'frontend route failed'}
$fa=Invoke-WebRequest -UseBasicParsing "$FrontendUrl/api/crm/foundation/campaigns" -TimeoutSec 15;if($fa.StatusCode-ne200){throw 'frontend proxy failed'}
$lat=@($all|?{$_.Path-like'/api/crm/foundation/campaigns*'});$sort=@($lat|Sort-Object Ms);$avg=[math]::Round(($lat|Measure-Object Ms -Average).Average,2);$min=($lat|Measure-Object Ms -Minimum).Minimum;$p95=$sort[[math]::Min($sort.Count-1,[math]::Ceiling($sort.Count*.95)-1)].Ms
[pscustomobject]@{S1506Decision='Implemented';LocalBackendUrl=$BaseUrl;LocalFrontendUrl=$FrontendUrl;FrontendApiRoutingMode='Proxy';BackendHealth='PASS';FrontendCampaignRouteStatus=200;FrontendToCampaignApiConnectivity='PASS';InitialCampaignCount=$initial;CreatedCampaignId=$id;CreateScenario='PASS';ReadAfterCreate='PASS';UpdateScenario='PASS';NoChangeScenario='PASS';InvalidRangeScenario='PASS';NotFoundScenario='PASS';ActivateScenario='PASS';RepeatActivate='PASS';ActiveUpdateRejected='PASS';CompleteScenario='PASS';RepeatComplete='PASS';CancelScenario='PASS';RepeatCancel='PASS';CancelledUpdateRejected='PASS';ReadAfterWriteConsistent=$true;ProductiveCampaignRouteAvailable=$false;DeleteRouteAvailable=$false;RuntimePersistenceClassification='FoundationOnly';PortalRuntimeObserved=$false;TokenRuntimeObserved=$false;CommonDbRuntimeObserved=$false;ExternalConnectorRuntimeObserved=$false;RealDataDetected=$false;SimulatedProductionTouched=$false;IntegrationLatencySamples=$lat.Count;LatencyMinMs=$min;LatencyAverageMs=$avg;LatencyP95Ms=$p95;RunId=$run}|ConvertTo-Json -Depth 4
