param([string]$BaseUrl='http://localhost:8093',[string]$FrontendUrl='http://127.0.0.1:4200')
$ErrorActionPreference='Stop'
function Req([string]$Method,[string]$Path,[object]$Body=$null){$sw=[Diagnostics.Stopwatch]::StartNew();try{$a=@{UseBasicParsing=$true;Method=$Method;Uri="$BaseUrl$Path";TimeoutSec=15};if($null-ne$Body){$a.Body=$Body|ConvertTo-Json -Depth 5 -Compress;$a.ContentType='application/json'};$r=Invoke-WebRequest @a;$sw.Stop();[pscustomobject]@{Method=$Method;Path=$Path;Status=[int]$r.StatusCode;Ms=$sw.ElapsedMilliseconds;Body=$r.Content}}catch{$sw.Stop();$s=0;$b='';if($_.Exception.Response){$s=[int]$_.Exception.Response.StatusCode};if($_.ErrorDetails.Message){$b=$_.ErrorDetails.Message};[pscustomobject]@{Method=$Method;Path=$Path;Status=$s;Ms=$sw.ElapsedMilliseconds;Body=$b}}}
function Ok($r,[int[]]$expected,[string]$name){if($r.Status -notin $expected){throw "$name expected $($expected -join '/') got $($r.Status): $($r.Body)"}}
$run=[guid]::NewGuid().ToString('N').Substring(0,8);$all=New-Object System.Collections.Generic.List[object]
foreach($p in @('/health','/health/live','/health/ready')){$r=Req GET $p;Ok $r @(200) "health $p";$all.Add($r)}
$list=Req GET '/api/crm/foundation/accounts';Ok $list @(200) 'initial list';$all.Add($list);$initial=@($list.Body|ConvertFrom-Json).Count
function Payload([string]$name,[string]$tax=' ec-100 ',[string]$industry=' Technology ',[string]$segment=' Enterprise '){return @{name=$name;taxId=$tax;industry=$industry;segment=$segment}}
$create=Req POST '/api/crm/foundation/accounts' (Payload "  S16 Integration Account $run  ");Ok $create @(200) 'create';$all.Add($create);$cj=$create.Body|ConvertFrom-Json;$id=$cj.id;if(!$id -or !$cj.changed -or $cj.account.name-ne"S16 Integration Account $run" -or $cj.account.taxId-ne'EC-100' -or $cj.account.status-ne'Draft'){throw 'create normalization failed'}
$detail=Req GET "/api/crm/foundation/accounts/$id";Ok $detail @(200) 'detail';$all.Add($detail)
$update=Req PUT "/api/crm/foundation/accounts/$id" (Payload "S16 Integration Account $run" ' ec-101 ' ' Finance ' ' MidMarket ');Ok $update @(200) 'update';$all.Add($update);if(-not($update.Body|ConvertFrom-Json).changed){throw 'update should change'}
$uj=$update.Body|ConvertFrom-Json;$no=Req PUT "/api/crm/foundation/accounts/$id" (Payload $uj.account.name $uj.account.taxId $uj.account.industry $uj.account.segment);Ok $no @(200) 'no change';$all.Add($no);if(($no.Body|ConvertFrom-Json).changed){throw 'no-change should be false'}
$bad=Req POST '/api/crm/foundation/accounts' (Payload '   ');Ok $bad @(400) 'invalid create';$all.Add($bad)
$missing=Req GET ("/api/crm/foundation/accounts/"+[guid]::NewGuid().ToString('D'));Ok $missing @(404) 'missing';$all.Add($missing)
$draftCreate=Req POST '/api/crm/foundation/accounts' (Payload "S16 Draft Conflict $run");Ok $draftCreate @(200) 'draft create';$all.Add($draftCreate);$draftId=($draftCreate.Body|ConvertFrom-Json).id
$draftDeactivate=Req POST "/api/crm/foundation/accounts/$draftId/deactivate";Ok $draftDeactivate @(409) 'draft deactivate conflict';$all.Add($draftDeactivate)
$activate=Req POST "/api/crm/foundation/accounts/$id/activate";Ok $activate @(200) 'activate';$all.Add($activate);if(($activate.Body|ConvertFrom-Json).account.status-ne'Active'){throw 'activate state invalid'}
$repeatActivate=Req POST "/api/crm/foundation/accounts/$id/activate";Ok $repeatActivate @(200) 'repeat activate';$all.Add($repeatActivate);if(($repeatActivate.Body|ConvertFrom-Json).changed){throw 'repeat activate changed'}$deactivate=Req POST "/api/crm/foundation/accounts/$id/deactivate";Ok $deactivate @(200) 'deactivate';$all.Add($deactivate);if(($deactivate.Body|ConvertFrom-Json).account.status-ne'Inactive'){throw 'deactivate state invalid'}
$repeatDeactivate=Req POST "/api/crm/foundation/accounts/$id/deactivate";Ok $repeatDeactivate @(200) 'repeat deactivate';$all.Add($repeatDeactivate);if(($repeatDeactivate.Body|ConvertFrom-Json).changed){throw 'repeat deactivate changed'}
$list2=Req GET '/api/crm/foundation/accounts';Ok $list2 @(200) 'list after';$all.Add($list2);$ids=@(($list2.Body|ConvertFrom-Json)|%{$_.id});foreach($x in @($id,$draftId)){if($ids -notcontains $x){throw "list missing $x"}}
foreach($n in @(@('GET','/api/crm/accounts'),@('POST','/api/crm/accounts'),@('PUT',"/api/crm/accounts/$id"),@('DELETE',"/api/crm/accounts/$id"))){$r=Req $n[0] $n[1];Ok $r @(404) "productive $($n[0])";$all.Add($r)}
$fd=Req DELETE "/api/crm/foundation/accounts/$id";Ok $fd @(404,405) 'foundation delete';$all.Add($fd)
$fr=Invoke-WebRequest -UseBasicParsing "$FrontendUrl/foundation/accounts" -TimeoutSec 15;if($fr.StatusCode-ne200){throw 'frontend route failed'}
$fa=Invoke-WebRequest -UseBasicParsing "$FrontendUrl/api/crm/foundation/accounts" -TimeoutSec 15;if($fa.StatusCode-ne200){throw 'frontend proxy failed'}
$lat=@($all|?{$_.Path-like'/api/crm/foundation/accounts*'});$sort=@($lat|Sort-Object Ms);$avg=[math]::Round(($lat|Measure-Object Ms -Average).Average,2);$min=($lat|Measure-Object Ms -Minimum).Minimum;$p95=$sort[[math]::Min($sort.Count-1,[math]::Ceiling($sort.Count*.95)-1)].Ms
[pscustomobject]@{S1606Decision='Implemented';LocalBackendUrl=$BaseUrl;LocalFrontendUrl=$FrontendUrl;FrontendApiRoutingMode='Proxy';BackendHealth='PASS';FrontendAccountRouteStatus=200;FrontendToAccountApiConnectivity='PASS';InitialAccountCount=$initial;CreatedAccountId=$id;CreateScenario='PASS';ReadAfterCreate='PASS';UpdateScenario='PASS';NoChangeScenario='PASS';InvalidCreateScenario='PASS';NotFoundScenario='PASS';DraftDeactivateRejected='PASS';ActivateScenario='PASS';RepeatActivate='PASS';DeactivateScenario='PASS';RepeatDeactivate='PASS';ReadAfterWriteConsistent=$true;ProductiveAccountRouteAvailable=$false;DeleteRouteAvailable=$false;RuntimePersistenceClassification='FoundationOnly';PortalRuntimeObserved=$false;CommonDbRuntimeObserved=$false;ExternalConnectorRuntimeObserved=$false;RealDataDetected=$false;SimulatedProductionTouched=$false;IntegrationLatencySamples=$lat.Count;LatencyMinMs=$min;LatencyAverageMs=$avg;LatencyP95Ms=$p95;RunId=$run}|ConvertTo-Json -Depth 4