param([string]$BaseUrl='http://localhost:8093',[string]$FrontendUrl='http://127.0.0.1:4200')
$ErrorActionPreference='Stop'
function Req([string]$Method,[string]$Path,[object]$Body=$null){$sw=[Diagnostics.Stopwatch]::StartNew();try{$a=@{UseBasicParsing=$true;Method=$Method;Uri="$BaseUrl$Path";TimeoutSec=15};if($null-ne$Body){$a.Body=$Body|ConvertTo-Json -Depth 5 -Compress;$a.ContentType='application/json'};$r=Invoke-WebRequest @a;$sw.Stop();[pscustomobject]@{Method=$Method;Path=$Path;Status=[int]$r.StatusCode;Ms=$sw.ElapsedMilliseconds;Body=$r.Content}}catch{$sw.Stop();$s=0;$b='';if($_.Exception.Response){$s=[int]$_.Exception.Response.StatusCode};if($_.ErrorDetails.Message){$b=$_.ErrorDetails.Message};[pscustomobject]@{Method=$Method;Path=$Path;Status=$s;Ms=$sw.ElapsedMilliseconds;Body=$b}}}
function Ok($r,[int[]]$expected,[string]$name){if($r.Status -notin $expected){throw "$name expected $($expected -join '/') got $($r.Status): $($r.Body)"}}
$run=[guid]::NewGuid().ToString('N').Substring(0,8);$all=New-Object System.Collections.Generic.List[object];$customer='11111111-1111-1111-1111-111111111111'
foreach($p in @('/health','/health/live','/health/ready')){$r=Req GET $p;Ok $r @(200) "health $p";$all.Add($r)}
$list=Req GET '/api/crm/foundation/cases';Ok $list @(200) 'initial list';$all.Add($list);$initial=@($list.Body|ConvertFrom-Json).Count
function Payload([string]$title,[string]$summary=' Synthetic integration case ',[string]$priority='High'){return @{customerId=$customer;title=$title;summary=$summary;priority=$priority}}
$create=Req POST '/api/crm/foundation/cases' (Payload "  S18 Integration Case $run  ");Ok $create @(200) 'create';$all.Add($create);$cj=$create.Body|ConvertFrom-Json;$id=$cj.id;if(!$id -or !$cj.changed -or $cj.case.title-ne"S18 Integration Case $run" -or $cj.case.summary-ne'Synthetic integration case' -or $cj.case.status-ne'Open'){throw 'create normalization failed'}
$detail=Req GET "/api/crm/foundation/cases/$id";Ok $detail @(200) 'detail';$all.Add($detail)
$update=Req PUT "/api/crm/foundation/cases/$id" (Payload "S18 Integration Case $run" ' Updated integration summary ' 'Critical');Ok $update @(200) 'update';$all.Add($update);if(-not($update.Body|ConvertFrom-Json).changed){throw 'update should change'}
$uj=$update.Body|ConvertFrom-Json;$no=Req PUT "/api/crm/foundation/cases/$id" @{customerId=$customer;title=$uj.case.title;summary=$uj.case.summary;priority=$uj.case.priority};Ok $no @(200) 'no change';$all.Add($no);if(($no.Body|ConvertFrom-Json).changed){throw 'no-change should be false'}
$bad=Req POST '/api/crm/foundation/cases' @{customerId='bad';title='Bad';summary='Bad customer';priority='Medium'};Ok $bad @(400) 'invalid create';$all.Add($bad)
$missingId=[guid]::NewGuid().ToString('D');$missing=Req GET "/api/crm/foundation/cases/$missingId";Ok $missing @(404) 'missing';$all.Add($missing)
$conflictCreate=Req POST '/api/crm/foundation/cases' (Payload "S18 Conflict $run");Ok $conflictCreate @(200) 'conflict create';$all.Add($conflictCreate);$conflictId=($conflictCreate.Body|ConvertFrom-Json).id
$conflict=Req POST "/api/crm/foundation/cases/$conflictId/close";Ok $conflict @(409) 'open close conflict';$all.Add($conflict)
$start=Req POST "/api/crm/foundation/cases/$id/start";Ok $start @(200) 'start';$all.Add($start);if(($start.Body|ConvertFrom-Json).case.status-ne'InProgress'){throw 'start state invalid'}
$repeatStart=Req POST "/api/crm/foundation/cases/$id/start";Ok $repeatStart @(200) 'repeat start';$all.Add($repeatStart);if(($repeatStart.Body|ConvertFrom-Json).changed){throw 'repeat start changed'}
$resolve=Req POST "/api/crm/foundation/cases/$id/resolve";Ok $resolve @(200) 'resolve';$all.Add($resolve);if(($resolve.Body|ConvertFrom-Json).case.status-ne'Resolved'){throw 'resolve state invalid'}
$repeatResolve=Req POST "/api/crm/foundation/cases/$id/resolve";Ok $repeatResolve @(200) 'repeat resolve';$all.Add($repeatResolve);if(($repeatResolve.Body|ConvertFrom-Json).changed){throw 'repeat resolve changed'}
$closed=Req POST "/api/crm/foundation/cases/$id/close";Ok $closed @(200) 'close';$all.Add($closed);if(($closed.Body|ConvertFrom-Json).case.status-ne'Closed'){throw 'close state invalid'}
$repeatClose=Req POST "/api/crm/foundation/cases/$id/close";Ok $repeatClose @(200) 'repeat close';$all.Add($repeatClose);if(($repeatClose.Body|ConvertFrom-Json).changed){throw 'repeat close changed'}
$detail2=Req GET "/api/crm/foundation/cases/$id";Ok $detail2 @(200) 'read after write';$all.Add($detail2);if(($detail2.Body|ConvertFrom-Json).status-ne'Closed'){throw 'read-after-write inconsistent'}
foreach($n in @(@('GET','/api/crm/cases'),@('POST','/api/crm/cases'),@('PUT',"/api/crm/cases/$id"),@('DELETE',"/api/crm/cases/$id"))){$r=Req $n[0] $n[1];Ok $r @(404) "productive $($n[0])";$all.Add($r)}
$fd=Req DELETE "/api/crm/foundation/cases/$id";Ok $fd @(404,405) 'foundation delete';$all.Add($fd)
$fr=Invoke-WebRequest -UseBasicParsing "$FrontendUrl/foundation/cases" -TimeoutSec 15;if($fr.StatusCode-ne200){throw 'frontend route failed'}
$fa=Invoke-WebRequest -UseBasicParsing "$FrontendUrl/api/crm/foundation/cases" -TimeoutSec 15;if($fa.StatusCode-ne200){throw 'frontend proxy failed'}
$lat=@($all|?{$_.Path-like'/api/crm/foundation/cases*'});$sort=@($lat|Sort-Object Ms);$avg=[math]::Round(($lat|Measure-Object Ms -Average).Average,2);$min=($lat|Measure-Object Ms -Minimum).Minimum;$p95=$sort[[math]::Min($sort.Count-1,[math]::Ceiling($sort.Count*.95)-1)].Ms
[pscustomobject]@{S1806Decision='Implemented';LocalBackendUrl=$BaseUrl;LocalFrontendUrl=$FrontendUrl;FrontendApiRoutingMode='Proxy';BackendHealth='PASS';FrontendCaseRouteStatus=200;FrontendToCaseApiConnectivity='PASS';InitialCaseCount=$initial;CreatedCaseId=$id;CreateScenario='PASS';ReadAfterCreate='PASS';UpdateScenario='PASS';NoChangeScenario='PASS';InvalidCreateScenario='PASS';NotFoundScenario='PASS';InvalidTransitionScenario='PASS';StartScenario='PASS';RepeatStart='PASS';ResolveScenario='PASS';RepeatResolve='PASS';CloseScenario='PASS';RepeatClose='PASS';ReadAfterWriteConsistent=$true;ProductiveCaseRouteAvailable=$false;DeleteRouteAvailable=$false;RuntimePersistenceClassification='FoundationOnly';CustomerMutationObserved=$false;AssignmentRuntimeObserved=$false;SlaRuntimeObserved=$false;NotificationRuntimeObserved=$false;PortalRuntimeObserved=$false;CommonDbRuntimeObserved=$false;ExternalConnectorRuntimeObserved=$false;RealDataDetected=$false;SimulatedProductionTouched=$false;IntegrationLatencySamples=$lat.Count;LatencyMinMs=$min;LatencyAverageMs=$avg;LatencyP95Ms=$p95;RunId=$run}|ConvertTo-Json -Depth 4
