param([string]$BaseUrl='http://localhost:8093',[string]$FrontendUrl='http://127.0.0.1:4200')
$ErrorActionPreference='Stop'
function Req([string]$Method,[string]$Path,[object]$Body=$null){$sw=[Diagnostics.Stopwatch]::StartNew();try{$a=@{UseBasicParsing=$true;Method=$Method;Uri="$BaseUrl$Path";TimeoutSec=15};if($null-ne$Body){$a.Body=$Body|ConvertTo-Json -Depth 8 -Compress;$a.ContentType='application/json'};$r=Invoke-WebRequest @a;$sw.Stop();[pscustomobject]@{Method=$Method;Path=$Path;Status=[int]$r.StatusCode;Ms=$sw.ElapsedMilliseconds;Body=$r.Content}}catch{$sw.Stop();$s=0;$b='';if($_.Exception.Response){$s=[int]$_.Exception.Response.StatusCode};if($_.ErrorDetails.Message){$b=$_.ErrorDetails.Message};[pscustomobject]@{Method=$Method;Path=$Path;Status=$s;Ms=$sw.ElapsedMilliseconds;Body=$b}}}
function Ok($r,[int[]]$expected,[string]$name){if($r.Status -notin $expected){throw "$name expected $($expected -join '/') got $($r.Status): $($r.Body)"}}
$pipe='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';$s1='cccccccc-cccc-cccc-cccc-cccccccccccc';$s2='dddddddd-dddd-dddd-dddd-dddddddddddd';$s3='eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee';$s4='ffffffff-ffff-ffff-ffff-ffffffffffff'
$stages=@(@{stageId=$s1;name='Qualification';order=1},@{stageId=$s2;name='Proposal';order=2},@{stageId=$s3;name='Negotiation';order=3},@{stageId=$s4;name='Commit';order=4})
$run=[guid]::NewGuid().ToString('N').Substring(0,8);$all=New-Object System.Collections.Generic.List[object]
foreach($p in @('/health','/health/live','/health/ready')){$r=Req GET $p;Ok $r @(200) "health $p";$all.Add($r)}
$list=Req GET '/api/crm/foundation/opportunities';Ok $list @(200) 'initial list';$all.Add($list);$initial=@($list.Body|ConvertFrom-Json).Count
function Payload([string]$name,[decimal]$value=25000,[int]$prob=25,[string]$stage=$s1,[string]$currency='usd'){return @{accountName=$name;expectedValue=$value;currency=$currency;probability=$prob;pipelineId=$pipe;stageId=$stage;stages=$stages;leadId=$null;contactId=$null;accountId=$null;activityId=$null}}
$create=Req POST '/api/crm/foundation/opportunities' (Payload "  S14 Integration Deal $run  ");Ok $create @(200) 'create';$all.Add($create);$cj=$create.Body|ConvertFrom-Json;$id=$cj.id;if(!$id -or !$cj.changed -or $cj.opportunity.accountName -ne "S14 Integration Deal $run" -or $cj.opportunity.currency -ne 'USD'){throw 'create normalization failed'}
$detail=Req GET "/api/crm/foundation/opportunities/$id";Ok $detail @(200) 'detail';$all.Add($detail)
$update=Req PUT "/api/crm/foundation/opportunities/$id" (Payload "S14 Integration Deal $run" 31000 35);Ok $update @(200) 'update';$all.Add($update);if(-not($update.Body|ConvertFrom-Json).changed){throw 'update should change'}
$uj=$update.Body|ConvertFrom-Json;$no=Req PUT "/api/crm/foundation/opportunities/$id" (Payload $uj.opportunity.accountName $uj.opportunity.expectedValue $uj.opportunity.probability $uj.opportunity.stageId $uj.opportunity.currency);Ok $no @(200) 'no change';$all.Add($no);if(($no.Body|ConvertFrom-Json).changed){throw 'no-change should be false'}
$prog=Req POST "/api/crm/foundation/opportunities/$id/progress" @{stageId=$s2;stages=$stages};Ok $prog @(200) 'progress next';$all.Add($prog);if(($prog.Body|ConvertFrom-Json).opportunity.stageId -ne $s2){throw 'next stage not persisted'}
$same=Req POST "/api/crm/foundation/opportunities/$id/progress" @{stageId=$s2;stages=$stages};Ok $same @(400) 'same stage';$all.Add($same)
$skip=Req POST "/api/crm/foundation/opportunities/$id/progress" @{stageId=$s4;stages=$stages};Ok $skip @(400) 'skip stage';$all.Add($skip)
function NewOpp([string]$suffix){$r=Req POST '/api/crm/foundation/opportunities' (Payload "S14 $suffix $run");Ok $r @(200) "create $suffix";$all.Add($r);return ($r.Body|ConvertFrom-Json).id}
$winId=NewOpp 'Win';$win=Req POST "/api/crm/foundation/opportunities/$winId/win";Ok $win @(200) 'win';$all.Add($win);$wj=$win.Body|ConvertFrom-Json;if($wj.status-ne'Won'-or$wj.opportunity.probability-ne100){throw 'win state invalid'};$rw=Req POST "/api/crm/foundation/opportunities/$winId/win";Ok $rw @(200) 'repeat win';$all.Add($rw);if(($rw.Body|ConvertFrom-Json).changed){throw 'repeat win changed'}
$loseId=NewOpp 'Lose';$lose=Req POST "/api/crm/foundation/opportunities/$loseId/lose";Ok $lose @(200) 'lose';$all.Add($lose);$rl=Req POST "/api/crm/foundation/opportunities/$loseId/lose";Ok $rl @(200) 'repeat lose';$all.Add($rl);if(($rl.Body|ConvertFrom-Json).changed){throw 'repeat lose changed'}
$cancelId=NewOpp 'Cancel';$can=Req POST "/api/crm/foundation/opportunities/$cancelId/cancel";Ok $can @(200) 'cancel';$all.Add($can);$rc=Req POST "/api/crm/foundation/opportunities/$cancelId/cancel";Ok $rc @(200) 'repeat cancel';$all.Add($rc);if(($rc.Body|ConvertFrom-Json).changed){throw 'repeat cancel changed'}
$tu=Req PUT "/api/crm/foundation/opportunities/$winId" (Payload 'Terminal update' 1 1);Ok $tu @(400) 'terminal update';$all.Add($tu);$tp=Req POST "/api/crm/foundation/opportunities/$winId/progress" @{stageId=$s2;stages=$stages};Ok $tp @(400) 'terminal progress';$all.Add($tp)
$missing=Req GET ("/api/crm/foundation/opportunities/"+[guid]::NewGuid().ToString('D'));Ok $missing @(404) 'missing detail';$all.Add($missing)
$invalid=Req POST '/api/crm/foundation/opportunities' (Payload 'Invalid' -1 101 $s1 'XX');Ok $invalid @(400) 'invalid create';$all.Add($invalid)
$list2=Req GET '/api/crm/foundation/opportunities';Ok $list2 @(200) 'list after';$all.Add($list2);$ids=@(($list2.Body|ConvertFrom-Json)|%{$_.id});foreach($x in @($id,$winId,$loseId,$cancelId)){if($ids -notcontains $x){throw "list missing $x"}}
foreach($n in @(@('GET','/api/crm/opportunities'),@('POST','/api/crm/opportunities'),@('PUT',"/api/crm/opportunities/$id"),@('POST',"/api/crm/opportunities/$id/win"),@('DELETE',"/api/crm/opportunities/$id"))){$r=Req $n[0] $n[1];Ok $r @(404) "productive $($n[0])";$all.Add($r)}
$fd=Req DELETE "/api/crm/foundation/opportunities/$id";Ok $fd @(404,405) 'foundation delete';$all.Add($fd)
$fr=Invoke-WebRequest -UseBasicParsing "$FrontendUrl/foundation/opportunities" -TimeoutSec 15;if($fr.StatusCode-ne200){throw 'frontend route failed'};$fa=Invoke-WebRequest -UseBasicParsing "$FrontendUrl/api/crm/foundation/opportunities" -TimeoutSec 15;if($fa.StatusCode-ne200){throw 'frontend proxy failed'}
$lat=@($all|?{$_.Path-like'/api/crm/foundation/opportunities*'});$sort=@($lat|Sort-Object Ms);$avg=[math]::Round(($lat|Measure-Object Ms -Average).Average,2);$min=($lat|Measure-Object Ms -Minimum).Minimum;$p95=$sort[[math]::Min($sort.Count-1,[math]::Ceiling($sort.Count*.95)-1)].Ms
[pscustomobject]@{S1406Decision='Implemented';LocalBackendUrl=$BaseUrl;LocalFrontendUrl=$FrontendUrl;FrontendApiRoutingMode='Proxy';BackendHealth='PASS';FrontendOpportunityRouteStatus=200;FrontendToOpportunityApiConnectivity='PASS';InitialOpportunityCount=$initial;CreatedOpportunityId=$id;CreateScenario='PASS';ReadAfterCreate='PASS';UpdateScenario='PASS';NoChangeScenario='PASS';ProgressNextStage='PASS';SameStageRejected='PASS';SkipStageRejected='PASS';WinScenario='PASS';RepeatWin='PASS';LoseScenario='PASS';RepeatLose='PASS';CancelScenario='PASS';RepeatCancel='PASS';TerminalUpdateRejected='PASS';TerminalProgressRejected='PASS';NotFoundScenario='PASS';ValidationScenario='PASS';ReadAfterWriteConsistent=$true;ProductiveOpportunityRouteAvailable=$false;DeleteRouteAvailable=$false;RuntimePersistenceClassification='FoundationOnly';PortalRuntimeObserved=$false;TokenRuntimeObserved=$false;CommonDbRuntimeObserved=$false;RealDataDetected=$false;SimulatedProductionTouched=$false;IntegrationLatencySamples=$lat.Count;LatencyMinMs=$min;LatencyAverageMs=$avg;LatencyP95Ms=$p95;RunId=$run}|ConvertTo-Json -Depth 4
